### ISSUE TITLE
Cloudflare JS preventing API requests

### ISSUE THREAD

**Issue by erincerys** [AlexandreSenpai/NHentai-API#37]
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/discord/client.py", line 382, in _run_event
    await coro(*args, **kwargs)
  File "/usr/src/cables/cabling_bot/events/message_media_expand.py", line 356, in handle_message
    result = await self.handler_mapping[fqdn](msg, url)
  File "/usr/src/app/events/message_media_expand.py", line 189, in handle_nhentai_gallery
    response: Doujin = await self.nhentai.get_doujin(id=gallery_id)
  File "/usr/local/lib/python3.10/site-packages/NHentai/utils/cache.py", line 38, in wrapper
    new_execution = await function(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/NHentai/nhentai_async.py", line 41, in get_doujin
    SOUP = await self._async_fetch(urljoin(self._API_URL, f'gallery/{id}'), is_json=True)
  File "/usr/local/lib/python3.10/site-packages/NHentai/base_wrapper.py", line 46, in _async_fetch
    return await response.json() if is_json else BeautifulSoup("", 'html.parser')
  File "/usr/local/lib/python3.10/site-packages/aiohttp/client_reqrep.py", line 1103, in json
    raise ContentTypeError(
aiohttp.client_exceptions.ContentTypeError: 0, message='Attempt to decode JSON with unexpected mimetype: text/html; charset=utf-8', url=URL('https://nhentai.net/api/gallery/404970')
```

Reproducing the code path in python console, I see that the request is returning a Cloudflare protection page and HTTP 503.

```py
>>> import json
>>> import requests
>>> r = requests.get('https://nhentai.net/api/gallery/404970')
>>> r.json()
Traceback (most recent call last):
  File "/home/erin/.cache/pypoetry/virtualenvs/app-417_n4la-py3.10/lib/python3.10/site-packages/requests/models.py", line 910, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.10/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/erin/.cache/pypoetry/virtualenvs/app-417_n4la-py3.10/lib/python3.10/site-packages/requests/models.py", line 917, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: [Errno Expecting value] <!DOCTYPE HTML>
```
```html
...
    <h1><span data-translate="checking_browser">Checking your browser before accessing</span> nhentai.net.</h1>
...
```
```py
>>> r.status_code
503
```

I've reached out to nHentai directly, as I don't see any instructions on their site for hitting the API in an authenticated way to prevent this from happening.

**Comment by AlexandreSenpai** [comment]
Added on v1.0.2 version CloudFlare helpers to help to bypass these wrong validations by nhentai side.

Available at version:
pip3 install NHentai-API==1.0.2

Usage:
```py
from NHentai import NHentai, CloudFlareSettings

client = NHentai(request_settings=CloudFlareSettings(csrftoken="YOUR NHENTAI COOKIE TOKEN",
                                                     cf_clearance="YOUR NHENTAI COOKIE TOKEN"))
```

This works to both clients.
